Remove all the green checkmark ✔️ in the Content column #280
tungbq/devops-basic pull request #286
Opened 2023-09-18 17:34 UTC by dcompanykrish

> *Be noted that 280 is the issue ID*

## What is the purpose of the change

>All green checkmarks ✔️ in the Content column have been removed.
The table has been updated to reflect the change.

2023-09-19 13:51 UTC, tungbq reviewed
Seems like you mixed 2 separated tasks into one:
![image](https://github.com/tungbq/devops-basic/assets/85242618/60d898ed-15b9-40ab-9813-89a50033abcd)

We should keep 1 PR for each issue.
Could you please check and update this point?

2023-09-19 13:56 UTC, tungbq commented
> Thank you @dcompanykrish But it seems like you mixed 2 separated tasks into one: ![image](https://user-images.githubusercontent.com/85242618/268979206-60d898ed-15b9-40ab-9813-89a50033abcd.png)
> 
> We should keep 1 PR for each issue. Could you please check and update this point?

@dcompanykrish  Also, if you have some trouble with the Git usage, please refer to this guide https://github.com/tungbq/devops-basic/blob/main/CONTRIBUTING.md. Hope this help

2023-09-21 13:44 UTC, tungbq requested changes

2023-09-21 13:44 UTC, tungbq commented on topics/docker/README.md
> -# What is docker?
Please don't remove this file, can you double check? Thanks

2023-09-24 09:50 UTC, dcompanykrish commented
Hi @tungbq ,
I understand that we should not remove the file, and I have made the necessary changes to the PR to reflect this. 🔒

Please review the changes and let me know if you have any questions or concerns. 💬

2023-09-24 11:02 UTC, tungbq approved these changes
Great, thank you @dcompanykrish. Appreciate your great effort in this repo!
If you find this repository helpful, kindly consider showing your appreciation by giving it a star ⭐ Thanks! 💖

2023-09-24 11:02 UTC, merged